name: Deploy Project
on:
    pull_request:
        branches:
            - main
        types:
            - closed
    workflow_dispatch:
    push:
      branches:
          - main
      paths-ignore:
          - '.github/workflows/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Get code
          uses: actions/checkout@v3

        - name: Install dependencies
          run: npm ci

        - name: Lint
          run: npm run lint

        - name: Run tests
          run: npm run test

        - name: Build project
          run: npm run build

        - name: Deploy
          run: echo "Deploying ..."